### ISSUE TITLE
Bug rendering Java sources

### ISSUE THREAD

**Issue by jnfoster** [andrewcmyers/oodds#1]
From the main page (https://andrewcmyers.github.io/oodds/) the first example of a "Hello World" program shows the code for an interface for a priority queue instead.

<img width="776" alt="pq" src="https://user-images.githubusercontent.com/1843922/186568892-d3e83e72-ce03-4bac-82e0-0e65ed714e3e.png">

The source simply loads `Hello.java`:
```html
</p>
<pre class=load>
<a href="Hello.java">Hello.java</a>
</pre>
```
And there is only one file with the name `Hello.java`

The page renders fine when viewed from `lectures.html?id=objects` instead.

**Comment by andrewcmyers** [comment]
Fixed.
