### ISSUE TITLE
constrain error?

### ISSUE THREAD

**Issue by jnfoster** [andrewcmyers/oodds#3]
Evaluation of the `constrain` graphics in the [complexity lecture](https://github.com/andrewcmyers/oodds/blob/main/lectures/complexity/index.html#L17) is causing an exception to be thrown in [lecture.js](https://github.com/andrewcmyers/oodds/blob/main/js/lectures.js#L86). And so the graphics are not being drawn and the animation doesn't work.

As someone whose knowledge of `constrain` is limited to a 5-minute faculty lunch talk, I'm not exactly sure how best to debug this, except crude delta debugging on the constrain code itself. Any advice?

**Comment by andrewcmyers** [comment]
I'll take a look. Probably an easy fix.

**Comment by andrewcmyers** [comment]
fixed
